baseURL = "http://example.org/"
languageCode = "en-us"
title = "Blog"
copyright = "Kostas Vasilopoulos"
theme = "diary"
# googleAnalytics = "UA-123-45"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
subtitle = "By Kostas Vasilopoulos"
enableGitalk = false

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   # tag = "tags"
   economics = "economics"
   econometrics = "econometrics"
   rpkg = "Rpackages"

[[menu.main]]
url = "/posts"
names = "Archive"


[[menu.main]]
url = "/economics"
name = "Economics"
weight = 1

# [[menu.main]]
# url = "/econometrics"
# name = "Econometrics"
# weight = 2

# [[menu.main]]
# url = "/rpackages"
# name = "R packages"
# weight = 3

# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 4
